### ISSUE TITLE
Test on UCFRep

### ISSUE THREAD

**Issue by isotopezzq** [SvipRepetitionCounting/TransRAC#28]
![image](https://user-images.githubusercontent.com/63627336/195322556-294872b7-1694-4fe2-a2a2-64159d2ecf3d.png)
I want to test the model on the UCFRep. How should I reorganize the UCFRep so I can use the UCFRep_loader.py

**Comment by isotopezzq** [comment]
And How do I get the ucfval.csv
![image](https://user-images.githubusercontent.com/63627336/195323712-79f9bc84-846f-47bc-acc2-25bbb92333d8.png)

**Comment by ZYQbill** [comment]
Hi, sorry for the late reply. I try to find my preprocessed ucfval.csv but failed, since I am not following this work anymore, and the disk of our gpu cluster was cleaned once.  

In the file of these .mat, the label is something like: [0, 9, 12, 20], which means that it should be changed into [0 9 9 12 12 20] in our label format. By doing this in matlab, you can get the ucfval.csv. I believe it is not hard to implement this. If you have any other questions, you can still ask me here.
