### ISSUE TITLE
Logical error in video2npz and access to RepCountB

### ISSUE THREAD

**Issue by sanchit2843** [SvipRepetitionCounting/TransRAC#37]
Hi, 
Would really appreciate if you can shed some light on this. 
https://github.com/SvipRepetitionCounting/TransRAC/blob/47a19be5517847c8efa2807913915876517af9ab/tools/video2npz.py#L134

In this line you changed the order of the batch of numpy array, it was changed from # [f,h,w,c] -> # [f,c,h,w] but from my understanding you transposed the array using (0,3,2,1) instead of (0,3,1,2), which will rearrange the height and width and thus will create images which are rotated. 
Also I couldn't find the repcountB dataset for testing the model, would really appreciate if you can share a link to it.
Regards

**Comment by Ironieser** [comment]
Thx for your question, https://github.com/SvipRepetitionCounting/TransRAC/blob/47a19be5517847c8efa2807913915876517af9ab/tools/video2npz.py#L118-L132
The problem is this line's comments. After cv2.read(), and cv2.resize(), the frames shape is [b,w,h,c] rather than [b,h,w,c], the comment is wrong but the code is right.

**Comment by sanchit2843** [comment]
Hey though I don't understand why it would be [b,w,h,c], I tried plotting the results and the image is getting rotated horizontally after line 134. I am not sure if you are rotating it later in dataloader but I tried replicating the results and haven't gotten the results as expected. I would really appreciate it if you can check it on your end. 
Regards
