### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '\xef'.

### ISSUE THREAD

**Issue by Y-Claw** [SvipRepetitionCounting/TransRAC#4]
When I run train.py, it raise "_pickle.UnpicklingError: invalid load key, '\xef'." I tried to load it on two different computer but same error occur. Could you confirm that there is no problem with the uploaded checkpoint file. Thank you very much.

**Comment by 957001934** [comment]
I am sorry. Due to the uploading limitation of  github, the pre-uploaded checkpoint of video swin transformer is broken. You need to load the pretrained model from https://github.com/SwinTransformer/storage/releases/download/v1.0.4/swin_tiny_patch244_window877_kinetics400_1k.pth , and place it in the **'pretrained'** folder.

**Comment by Y-Claw** [comment]
OK,thank you very much.
